### PR TITLE
Adds the pdf link (to my GitHub page) for the MSR paper. 

### PR DESCRIPTION
**Pull request by AntonisGkortzis**
Adds MSR18 paper download url from personal GitHub page

### CODE REVIEW

**Comment by dspinellis** [comment]
@AntonisGkortzis, Thank you! Please note that commit b08543c5d9fd88f8ed9efffdaa5bee34ac58c5f6 should have been a merge, rather than the addition of the conflicting data from you. Please submit a single clean commit on the correct base.

**Comment by AntonisGkortzis** [comment]
I created a new pull request with only my addition in the commit. You can discard this pull request.

**Comment by dspinellis** [comment]
Note that you could have amended this pull request with `git reset` to the point where you missed the merge.

**Comment by AntonisGkortzis** [comment]
I agree with you. I chose this approach only based on the least number of steps for committing again. 
I'll stick to the formal way the next time.

**Pull request closed without merging**
