### PR TITLE
ESEC-FSE 2019 publication

### PR DESCRIPTION
**Pull request by CHM1993**

### CODE REVIEW

**Comment by dspinellis** [comment]
Sorry for leaving this pending.  Please 
* [ ] Clarify the conference's track and the publication's type
* [ ] Resolve the merge conflicts
* [ ] Squash the commits into one

**Comment by dspinellis** [comment]
Thank you.  Please squash your commits into a single clean one, so that I can review it.

**Comment by CHM1993** [comment]
What is the field that I should put the conference tack and publication
type. I can not find them in templates.
Thank you.

**Comment by dspinellis** [comment]
It is part of the conference structure, not the template. Look at other similar publications.

**Pull request merged**
