### PR TITLE
Added Dr.Yiannis Mourtos as member and his  publications

### PR DESCRIPTION
**Pull request by stefanos1316**
Hello Prof., 

I added Dr. Yiannis Mourtos's information in our repo.

### CODE REVIEW

**Comment by dspinellis** [comment]
Note that you accidentally committed `content/.pubs.bib.swp`.

**Comment by stefanos1316** [comment]
Yes Prof., I 'm removing them now. 
Moreover, I tested it locally and I have found some problems regarding missing fields that I corrected. 

In addition, in the 'Conference Publications' Section, there are such bullets as:

- Proceeding of AMBS Big Data Forum
- Proceedings of 13th Student Conference of Management Science and Technology
- Proceedings of 13th Student Conference of Management Science and Technology
.....
and so on

From a short observation I did, I found out that these bullets (which are showed as publications) occurred from the "Organization" bibtex's field and more specifically from Anastasia Griva's input. 
She is using the @Proceedings tag instead of @inproceedings. 

I tried to change it but the field "Booktitle" is required for the @inproceedings tag. 
Should I inform her to make the changes?

**Comment by dspinellis** [comment]
Yes, please inform her.

Also, can you please see whether you can setup TravisCI on this repo to avoid failed build problems?

**Comment by stefanos1316** [comment]
Yes, I will do both and let you know.

**Comment by stefanos1316** [comment]
Prof. Spinellis, 

1) I have sent a mail to Anastasis.
2) I read a tutorial about TravisCI and developed a file [.travis.yml](https://github.com/stefanos1316/web/blob/master/.travis.yml) where I do install all the necessary packages for our repo (as specified in **web site installation and deployment**). 
In addition, I changed the BASE's variable path under the bin/update script. 
From the TravisCI test I get the following output:

`9.02s$ sudo ./bin/update
mkdir: cannot create directory ‘balab/new’: No such file or directory
chgrp: invalid group: ‘iweb’
chmod: cannot access ‘balab/new’: No such file or directory
WARNING: JINJA_EXTENSIONS setting has been deprecated, moving it to JINJA_ENVIRONMENT setting.
Done: Processed 82 articles, 0 drafts, 4 pages and 0 hidden pages in 8.83 seconds.
mv: cannot stat ‘balab/current’: No such file or directory
The command "sudo ./bin/update" exited with 0.
Done. Your build exited with 0.`

Seems the pelecan creates the files normally. 
When I test it locally it creates the  **balab** directory normally and shows the web-site as expected.

I am creating a pull-request now, feel free to inform me about any changes on this!

**Comment by dspinellis** [comment]
Amazing, well done!  Consider changing the behavior of the update script depending on whether it runs on istlab (`test $(hostname) == istlab`) or not.

Also, consider testing the sizes of a few key files, as a sanity check.  E.g.
```
test $(stat -c %s $BASE/current/category/members.html) -gt 20000
test $(stat -c %s $BASE/current/category/software.html) -gt 7000
test $(stat -c %s $BASE/current/category/projects.html) -gt 10000
test $(stat -c %s $BASE/current/category/alumni.html) -gt 5000
test $(stat -c %s $BASE/current/category/yearly-reports.html) -gt 5000
```

**Comment by stefanos1316** [comment]
So if it runs on the **istlab** which behaviour exactly should I change? 
Maybe you mean the **chgrp** command?

About the second test, should we send a warning message or not allow the execution of the script if that is the case?

**Comment by dspinellis** [comment]
On *istlab* the behavior should be as it was before you started CI.  When not on istlab, you need to remove commands that don't make sense, e.g. `chgrp`.

If tests fail then CI should fail / the contents should not get installed.

**Comment by stefanos1316** [comment]
Take a look on this Prof. [update](https://github.com/stefanos1316/web/blob/master/bin/update) and let me know if you would like me to change it.

**Comment by dspinellis** [comment]
A lot of work! Two comments:

* The goal of the tests, is not to verify that there is enough disk space (we assume there is), but that the file has been generated correctly, i.e. that its minimum size is correct.
* As an aside, wouldn't it be easier, instead of parsing the output of `df -h` to avoid the `-h` flag?

**Comment by stefanos1316** [comment]
* Okay, I have changed the script, have a look [here](https://github.com/stefanos1316/web/blob/master/bin/update), now the script checks if the files were created correctly, otherwise it informs the user to check them again.
* Yes, it was my mistake of adding the `df -h`, I could easily ignore it and avoid the whole mess.

**Comment by dspinellis** [comment]
Sounds good.  These changes are all still in your repo.  Please do a rebase to merge them into a single logical commit and issue a pull request.

**Comment by stefanos1316** [comment]
Okay, I used the `git rebase -i HEAD~my_number_of_commits` and I created the pull request, however, it is the first time I am attempting such an action, if there is something wrong let me know.

**Pull request merged**
