### PR TITLE
Adding best paper award event

### PR DESCRIPTION
**Pull request by stefanos1316**

### CODE REVIEW

**Comment by stefanos1316** [comment]
Best paper award event added.

**Comment by dspinellis** [comment]
Don't link to the MSR publication; just use the publication's title.

**Comment by stefanos1316** [comment]
Okay, done!

**Comment by dspinellis** [comment]
You also uploaded a new picture, but with a name different from the existing one.  Please remove or correct.

**Comment by dspinellis** [comment]
In general, we want mugshots for the BALab staff pictures.

**Pull request merged**
